# Generated by Django 4.2.7 on 2023-11-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='info@circusrestaurant.se', max_length=100),
        ),
    ]
